### ISSUE TITLE
"Backing up world file..." Missing CRLF

### ISSUE THREAD

**Issue by D1G1T4L3CH0** [DeathCradle/Terraria-s-Dedicated-Server-Mod#87]
I found that every time the text `Backing up world file...` is displayed in the console, it's lacking a crlf. This results in concatenated text where it should not be and text that's not as easily read.

**Comment by D1G1T4L3CH0** [comment]
Still seems not fixed in b6b0de75f37acee8ae3096f71a93419a82fc2852
```
save-all
3/11/2015 1:43:30 AM Command> Saving world.....
Saving world data: 82%
Validating world save: 56%
Backing up world file...3/11/2015 1:43:30 AM Command> Saving data...
3/11/2015 1:43:30 AM Command> Saving Complete.
```

**Comment by DeathCradle** [comment]
This new line should be fixed in 332978ddc750d77c0e571c67ec7b418883f634d6.
Still a few issues, but it may just be the mono console (those strange characters). I should test in windows as well...

**Comment by D1G1T4L3CH0** [comment]
Not resolved. I get varying results. A lot of times it works fine. Other times the results are different each time. Below are some examples of results I have seen.

Windows.
```
Terraria Server v1.3.0.4

Listening on port 7777
Type 'help' for a list of commands.

7/12/2015 1:34:56 AM Command> Ready for commands.
exit
7/12/2015 1:34:57 AM Command> Exiting on request.

Saving world data: 100%7/12/2015 1:34:58 AM Run>
```

Linux
```
Terraria Server v1.3.0.4

Listening on port 7777
Type 'help' for a list of commands.

7/12/2015 1:30:18 AM Command> Ready for commands.
exit
7/12/2015 1:30:21 AM Command> Exiting on request.

Saving world data: 98%
Validating world save: 89%user@DragonSlayer:~/tdsm-rebind-test$

```

**Comment by DeathCradle** [comment]
[Update] For the automated save this has been resolved, but still exists upon exiting.

**Comment by DeathCradle** [comment]
[Update] I have played some more on this and managed to get OTA to hook the statusText updates. I'll close this off when fully completed (not thinking about making these as hooks since they should only ever be modified by one plugin)

**Comment by DeathCradle** [comment]
Moved out from B6 as this is not crucial for the update.
